logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            condition: trace
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
server:
  port: 8081
spring:
  cache:
    caffeine:
      spec: "initialCapacity=100,maximumSize=1000,expireAfterWrite=6000s,recordStats"
  redis:
    host: 192.168.1.121
